param([Parameter(Mandatory=$true)][string]$Installer)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression.FileSystem
$base = Split-Path $PSScriptRoot -Parent
$assembly = [Reflection.Assembly]::LoadFile((Resolve-Path -LiteralPath $Installer).Path)
$stream = $assembly.GetManifestResourceStream('payload.zip')
if (!$stream) { throw 'Embedded payload not found.' }
$zipPath = Join-Path $base 'payload.zip'
$out = [IO.File]::Open($zipPath,[IO.FileMode]::CreateNew)
try { $stream.CopyTo($out) } finally { $out.Dispose(); $stream.Dispose() }
# Only extract a trusted installer generated by this project.
[IO.Compression.ZipFile]::ExtractToDirectory($zipPath,(Join-Path $base 'payload'))
